file_format: "1"
id: switch_tester
name: switch_tester
type: shield
url: https://github.com/jenia90/zmk-config-dactyl-kinesis
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  # - display
  # - encoder
siblings:
  - switch_tester