file_format: "1"
id: dactyl_kinesis
name: dactyl_kinesis
type: shield
url: https://github.com/jenia90/zmk-config-dactyl-kinesis
requires: [pro_micro]
features:
  - keys
  # - display
  # - encoder
siblings:
  - dactyl_kinesis_left
  - dactyl_kinesis_right