on:
  push:
    paths: 
      - 'config/**'
      - 'build.yaml'
  pull_request:
    paths: 
      - 'config/**'
      - 'build.yaml'
  workflow_dispatch:
    paths: 
      - 'config/**'
      - 'build.yaml'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
